# Generated by Django 4.2.11 on 2024-08-29 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examinationapp', '0003_remove_lecture_user_examinationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExaminationUser',
        ),
    ]
