# Generated by Django 4.2.11 on 2024-08-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinationapp', '0004_lecture_user_delete_examinationuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
